### ISSUE TITLE
Which version of Carla simulator to use?

### ISSUE THREAD

**Issue by JackRen88** [enginBozkurt/MotionPlanner#1]
Hello.
I want to know that Which version of Carla simulator to use in the motion planner repo.
 Which article is referenced by the collision detection method?

**Comment by enginBozkurt** [comment]
You can run it in any version before 0.9.0

**Comment by enginBozkurt** [comment]
C. Urmson, C. Baker, J. Dolan, P. Rybski, B. Salesky, W. Whittaker, D. Ferguson, and M. Darms, “Autonomous Driving in Traffic: Boss and the Urban Challenge,” AI Magazine, vol. 30, no. 2, p. 17, 2009. This gives an overview of some of the methods used to handle dynamic obstacles in the DARPA Urban Challenge.
https://www.aaai.org/ojs/index.php/aimagazine/article/view/2238



Steven M Lavalle, Planning Algorithms, 2006, Cambridge University Press. Chapter 2 covers discrete planning over graphs including Dijkstra's and A*.
http://planning.cs.uiuc.edu


N. J. Nilsson, “Artificial intelligence: A modern approach,” Artificial Intelligence, vol. 82, no. 1-2, pp. 369–380, 1996. Read Chapters 3.4-3.5 for an overview of search algorithms in graphs.
http://aima.cs.berkeley.edu



S. Thrun, W. Burgard, and D. Fox, Probabilistic robotics. Cambridge, MA: MIT Press, 2010. Read Chapter 9 - Occupancy Grid Mapping for an overview of how occupancy grids are generated.
http://www.probabilistic-robotics.org

P. Bender, J. Ziegler, and C. Stiller, “Lanelets: Efficient map representation for autonomous driving,” 2014 IEEE Intelligent Vehicles Symposium Proceedings, 2014. Introduces the concepts of lanelets used in mapping.
http://static.aixpaper.com/pdf/d/f5/gs.2014.81cd3b9828.v1.pdf

N. Ratliff, M. Zucker, J. A. Bagnell, and S. Srinivasa, “CHOMP: Gradient optimization techniques for efficient motion planning,” 2009 IEEE International Conference on Robotics and Automation, 2009. Introduces the CHOMP algorithm as an example of applying calculus of variations to planning.
https://kilthub.cmu.edu/articles/CHOMP_Gradient_Optimization_Techniques_for_Efficient_Motion_Planning/6552254/1


J. Wei, J. M. Snider, T. Gu, J. M. Dolan, and B. Litkouhi, “A behavioral planning framework for autonomous driving,” 2014 IEEE Intelligent Vehicles Symposium Proceedings, 2014. This gives a nice overview of an example framework that can be used in behaviour planning.
https://ieeexplore.ieee.org/abstract/document/6856582



R. S. Sutton and A. G. Barto, Reinforcement learning an introduction. Cambridge: A Bradford Book, 1998. Gives a great introduction to reinforcement learning concepts.
http://incompleteideas.net/book/the-book-2nd.html


Fox, D.; Burgard, W.; Thrun, S. (1997). "The dynamic window approach to collision avoidance". Robotics & Automation Magazine, IEEE. 4 (1): 23–33. doi:10.1109/100.580977. This gives an overview of dynamic windowing and trajectory rollout.
https://ieeexplore.ieee.org/document/580977

**Comment by JackRen88** [comment]
Thank you for your reply!
 Do you use your own city map(such as /Game/Maps/Course4) instead of the official map in Carla? Is the map format that you used occupancy grid map or opendrive format? How can I run the motion planner you provide in Carla?

**Comment by enginBozkurt** [comment]
### **project file**
[vI0lpI0fEem-xg4p7cmXwA_e77ed940c64e410dbb04a66a123836d7_Course4FinalProject (1).zip](https://github.com/enginBozkurt/MotionPlanner/files/3661912/vI0lpI0fEem-xg4p7cmXwA_e77ed940c64e410dbb04a66a123836d7_Course4FinalProject.1.zip)

### **Installation and implementation guide**
[install.docx](https://github.com/enginBozkurt/MotionPlanner/files/3662091/install.docx)
