### ISSUE TITLE
Reference the source

### ISSUE THREAD

**Issue by NotAnyMike** [enginBozkurt/MotionPlanner#2]
You should probably give credit to Coursera, not just the University of Toronto. Also, you should mention the source of the pictures and the slides. And have you considered sharing the answer for one of the projects could go against the terms and conditions of coursera? Please consider that.

Apart from that, Well done man! Looks a very good solution to the project! And you also did a great job summarising the info. I hope you learn a lot and have fun with the project (:

**Comment by enginBozkurt** [comment]
@NotAnyMike I mentioned Self-Driving Cars Specialization which is only given through Coursera in the section of  Final Notes. But it can be inadequate information to indicate the Coursera platform directly. Thanks for remindings and suggestions. I am going to try to be more delicate and sensitive to give the credits to the related sources.
Appreciated for your valuable feedback.
