### ISSUE TITLE
live_plotter module missing

### ISSUE THREAD

**Issue by aravindSwamy94** [enginBozkurt/MotionPlanner#4]
Hi Bozkurt,
           Great Work!

But when I run this from your code , Im getting this error 

Traceback (most recent call last):
  File "module_7.py", line 41, in <module>
    import live_plotter as lv   # Custom live plotting library
ImportError: No module named 'live_plotter'

Basically it says live_plotter is missing. Could you please let me know the reason why this happens. I cannot find the file live_plotter.py anywhere in the web as well.

**Comment by enginBozkurt** [comment]
Thanks. That's very kind of you.

You could checkout these resources:

project file

https://github.com/enginBozkurt/MotionPlanner/files/3661912/vI0lpI0fEem-xg4p7cmXwA_e77ed940c64e410dbb04a66a123836d7_Course4FinalProject.1.zip

Installation and implementation guide
https://github.com/enginBozkurt/MotionPlanner/files/3662091/install.docx

I hope it helps with your error.

**Comment by aravindSwamy94** [comment]
Hi .. 
Ya tried to do that. Basically put that inside the PythonClient folder and run the module7.py.


But Im still getting this error. Basically it looks for live_plotter.py somewhere.. But im not sure where i can find it.. Should I install it in my system somewhere
