### ISSUE TITLE
Import Error No module named sensor 

### ISSUE THREAD

**Issue by AD1D1** [enginBozkurt/MotionPlanner#5]
Traceback (most recent call last):
  File "module_7.py", line 43, in <module>
    from carla            import sensor
ImportError: cannot import name 'sensor' from 'carla' (C:\Coursera\CarlaSimulator\PythonAPI\carla\dist\carla-0.9.10-py3.7-win-amd64.egg\carla\__init__.py)

pls help

**Comment by SafeDL** [comment]
> Traceback (most recent call last):
> File "module_7.py", line 43, in
> from carla import sensor
> ImportError: cannot import name 'sensor' from 'carla' (C:\Coursera\CarlaSimulator\PythonAPI\carla\dist\carla-0.9.10-py3.7-win-amd64.egg\carla__init__.py)
> 
> pls help

I have the same problem with you, maybe the carla version you uesed is too high, plz try carla 0.8.4

**Comment by AD1D1** [comment]
> > Traceback (most recent call last):
> > File "module_7.py", line 43, in
> > from carla import sensor
> > ImportError: cannot import name 'sensor' from 'carla' (C:\Coursera\CarlaSimulator\PythonAPI\carla\dist\carla-0.9.10-py3.7-win-amd64.egg\carla__init__.py)
> > pls help
> 
> I have the same problem with you, maybe the carla version you uesed is too high, plz try carla 0.8.4

Thanks for the response! How do I use a lower version of carla? Pls help

**Comment by enginBozkurt** [comment]
> > > Traceback (most recent call last):
> > > File "module_7.py", line 43, in
> > > from carla import sensor
> > > ImportError: cannot import name 'sensor' from 'carla' (C:\Coursera\CarlaSimulator\PythonAPI\carla\dist\carla-0.9.10-py3.7-win-amd64.egg\carla__init__.py)
> > > pls help
> > 
> > 
> > I have the same problem with you, maybe the carla version you uesed is too high, plz try carla 0.8.4
> 
> Thanks for the response! How do I use a lower version of carla? Pls help

You should need new installation for  0.8.4. 
You could checkout the releases here:
https://github.com/carla-simulator/carla/releases

**Comment by AD1D1** [comment]
> > > > Traceback (most recent call last):
> > > > File "module_7.py", line 43, in
> > > > from carla import sensor
> > > > ImportError: cannot import name 'sensor' from 'carla' (C:\Coursera\CarlaSimulator\PythonAPI\carla\dist\carla-0.9.10-py3.7-win-amd64.egg\carla__init__.py)
> > > > pls help
> > > 
> > > 
> > > I have the same problem with you, maybe the carla version you uesed is too high, plz try carla 0.8.4
> > 
> > 
> > Thanks for the response! How do I use a lower version of carla? Pls help
> 
> You should need new installation for 0.8.4.
> You could checkout the releases here:
> https://github.com/carla-simulator/carla/releases

It's showing that the zip file for 0.8.4 doesn't exist anymore

**Comment by SafeDL** [comment]
> > > > > Traceback (most recent call last):
> > > > > File "module_7.py", line 43, in
> > > > > from carla import sensor
> > > > > ImportError: cannot import name 'sensor' from 'carla' (C:\Coursera\CarlaSimulator\PythonAPI\carla\dist\carla-0.9.10-py3.7-win-amd64.egg\carla__init__.py)
> > > > > pls help
> > > > 
> > > > 
> > > > I have the same problem with you, maybe the carla version you uesed is too high, plz try carla 0.8.4
> > > 
> > > 
> > > Thanks for the response! How do I use a lower version of carla? Pls help
> > 
> > 
> > You should need new installation for 0.8.4.
> > You could checkout the releases here:
> > https://github.com/carla-simulator/carla/releases
> 
> It's showing that the zip file for 0.8.4 doesn't exist anymore

I upload the carla simulator(version 0.8.4)  to baidu cloud disk ,you can have access to it
link：https://pan.baidu.com/s/1LHZZ2S2rfN2lQbkVDXxPqQ 
code：bnyq

**Comment by AD1D1** [comment]
> > > > > > Traceback (most recent call last):
> > > > > > File "module_7.py", line 43, in
> > > > > > from carla import sensor
> > > > > > ImportError: cannot import name 'sensor' from 'carla' (C:\Coursera\CarlaSimulator\PythonAPI\carla\dist\carla-0.9.10-py3.7-win-amd64.egg\carla__init__.py)
> > > > > > pls help
> > > > > 
> > > > > 
> > > > > I have the same problem with you, maybe the carla version you uesed is too high, plz try carla 0.8.4
> > > > 
> > > > 
> > > > Thanks for the response! How do I use a lower version of carla? Pls help
> > > 
> > > 
> > > You should need new installation for 0.8.4.
> > > You could checkout the releases here:
> > > https://github.com/carla-simulator/carla/releases
> > 
> > 
> > It's showing that the zip file for 0.8.4 doesn't exist anymore
> 
> I upload the carla simulator(version 0.8.4) to baidu cloud disk ,you can have access to it
> link：https://pan.baidu.com/s/1LHZZ2S2rfN2lQbkVDXxPqQ
> code：bnyq

Hey thanks for this.. but could you please upload it on a google drive, because Baidu cloud service is not accessible in my country, and using a VPN would really slow it down, I am sorry for the issue . Please

**Comment by SafeDL** [comment]
> > > > > > > Traceback (most recent call last):
> > > > > > > File "module_7.py", line 43, in
> > > > > > > from carla import sensor
> > > > > > > ImportError: cannot import name 'sensor' from 'carla' (C:\Coursera\CarlaSimulator\PythonAPI\carla\dist\carla-0.9.10-py3.7-win-amd64.egg\carla__init__.py)
> > > > > > > pls help
> > > > > > 
> > > > > > 
> > > > > > I have the same problem with you, maybe the carla version you uesed is too high, plz try carla 0.8.4
> > > > > 
> > > > > 
> > > > > Thanks for the response! How do I use a lower version of carla? Pls help
> > > > 
> > > > 
> > > > You should need new installation for 0.8.4.
> > > > You could checkout the releases here:
> > > > https://github.com/carla-simulator/carla/releases
> > > 
> > > 
> > > It's showing that the zip file for 0.8.4 doesn't exist anymore
> > 
> > 
> > I upload the carla simulator(version 0.8.4) to baidu cloud disk ,you can have access to it
> > link：https://pan.baidu.com/s/1LHZZ2S2rfN2lQbkVDXxPqQ
> > code：bnyq
> 
> Hey thanks for this.. but could you please upload it on a google drive, because Baidu cloud service is not accessible in my country, and using a VPN would really slow it down, I am sorry for the issue . Please

can you download by this link?
https://drive.google.com/file/d/1HDfcqFxP41L5hIUuKRTCUc45nxv3DmQA/view?usp=sharing

**Comment by AD1D1** [comment]
> > > > > > > > Traceback (most recent call last):
> > > > > > > > File "module_7.py", line 43, in
> > > > > > > > from carla import sensor
> > > > > > > > ImportError: cannot import name 'sensor' from 'carla' (C:\Coursera\CarlaSimulator\PythonAPI\carla\dist\carla-0.9.10-py3.7-win-amd64.egg\carla__init__.py)
> > > > > > > > pls help
> > > > > > > 
> > > > > > > 
> > > > > > > I have the same problem with you, maybe the carla version you uesed is too high, plz try carla 0.8.4
> > > > > > 
> > > > > > 
> > > > > > Thanks for the response! How do I use a lower version of carla? Pls help
> > > > > 
> > > > > 
> > > > > You should need new installation for 0.8.4.
> > > > > You could checkout the releases here:
> > > > > https://github.com/carla-simulator/carla/releases
> > > > 
> > > > 
> > > > It's showing that the zip file for 0.8.4 doesn't exist anymore
> > > 
> > > 
> > > I upload the carla simulator(version 0.8.4) to baidu cloud disk ,you can have access to it
> > > link：https://pan.baidu.com/s/1LHZZ2S2rfN2lQbkVDXxPqQ
> > > code：bnyq
> > 
> > 
> > Hey thanks for this.. but could you please upload it on a google drive, because Baidu cloud service is not accessible in my country, and using a VPN would really slow it down, I am sorry for the issue . Please
> 
> can you download by this link?
> https://drive.google.com/file/d/1HDfcqFxP41L5hIUuKRTCUc45nxv3DmQA/view?usp=sharing

Hey I have sent you the request to access the drive please accept it!

**Comment by ZhangTingyang** [comment]
请问如果不降低Carla的版本的话，可不可以实现呢？
